/**
 * Complete Andhra Pradesh Official Organizational Hierarchy Dataset
 * -----------------------------------------------------------------
 * Covers all 26 Districts, all 175 Assembly Constituencies, and their real Mandals
 * under Andhra Pradesh State.
 */

export const AP_COMPLETE_HIERARCHY = [
  {
    district: 'Srikakulam',
    code: 'AP-SKL',
    constituencies: [
      { name: 'Ichchapuram', mandals: ['Ichchapuram', 'Kaviti', 'Sompeta', 'Kanchili'] },
      { name: 'Palasa', mandals: ['Palasa', 'Mandasa', 'Vajrapukotturu'] },
      { name: 'Tekkali', mandals: ['Tekkali', 'Nandigam', 'Santhabommali', 'Kotabommali'] },
      { name: 'Pathapatnam', mandals: ['Pathapatnam', 'Meliaputti', 'L.N. Peta', 'Kothuru', 'Hiramandalam'] },
      { name: 'Srikakulam', mandals: ['Srikakulam', 'Gara'] },
      { name: 'Amadalavalasa', mandals: ['Amadalavalasa', 'Ponduru', 'Sarubujjili', 'Burja'] },
      { name: 'Etcherla', mandals: ['Etcherla', 'Laveru', 'Ranasthalam', 'G.Sigadam'] },
      { name: 'Narasannapeta', mandals: ['Narasannapeta', 'Jalumuru', 'Polaki', 'Saravakota'] },
    ],
  },
  {
    district: 'Vizianagaram',
    code: 'AP-VZM',
    constituencies: [
      { name: 'Rajam', mandals: ['Rajam', 'Vangara', 'Regidi Amadalavalasa', 'Santhakaviti'] },
      { name: 'Bobbili', mandals: ['Bobbili', 'Ramabhadrapuram', 'Badangi', 'Therlam'] },
      { name: 'Cheepurupalli', mandals: ['Cheepurupalli', 'Garividi', 'Gurla', 'Merakamudidam'] },
      { name: 'Gajapathinagaram', mandals: ['Gajapathinagaram', 'Bondapalli', 'Gantyada', 'Dattirajeru'] },
      { name: 'Nellimarla', mandals: ['Nellimarla', 'Pusapatirega', 'Denkada', 'Bhogapuram'] },
      { name: 'Vizianagaram', mandals: ['Vizianagaram Urban', 'Vizianagaram Rural'] },
      { name: 'Srungavarapukota', mandals: ['Srungavarapukota', 'Jami', 'Kothavalasa', 'Vepada', 'Lakkavarapukota'] },
    ],
  },
  {
    district: 'Parvathipuram Manyam',
    code: 'AP-PVP',
    constituencies: [
      { name: 'Palakonda', mandals: ['Palakonda', 'Seethampeta', 'Bhamini', 'Veeraghattam'] },
      { name: 'Kurupam', mandals: ['Kurupam', 'Gummalakshmipuram', 'Jiyyammavalasa', 'Komarada', 'Garugubilli'] },
      { name: 'Parvathipuram', mandals: ['Parvathipuram', 'Seethanagaram', 'Balijipeta'] },
      { name: 'Salur', mandals: ['Salur', 'Pachipenta', 'Mentada', 'Makkuva'] },
    ],
  },
  {
    district: 'Alluri Sitharama Raju',
    code: 'AP-ASR',
    constituencies: [
      { name: 'Araku Valley', mandals: ['Araku Valley', 'Dumbriguda', 'Hukumpeta', 'Ananthagiri', 'Pedabayalu', 'Munchingiputtu'] },
      { name: 'Paderu', mandals: ['Paderu', 'G.Madugula', 'Chintapalli', 'Gudem Kotha Veedhi', 'Koyyuru'] },
      { name: 'Rampachodavaram', mandals: ['Rampachodavaram', 'Devipatnam', 'Y. Ramavaram', 'Addateegala', 'Gangavaram', 'Maredumilli', 'Rajavommangi', 'Chintoor', 'Kunavaram', 'Vararamachandrapuram', 'Yetapaka'] },
    ],
  },
  {
    district: 'Visakhapatnam',
    code: 'AP-VSP',
    constituencies: [
      { name: 'Bheemunipatnam', mandals: ['Bheemunipatnam', 'Anandapuram', 'Padmanabham', 'Visakhapatnam Rural'] },
      { name: 'Visakhapatnam East', mandals: ['Visakhapatnam East Urban', 'MVP Colony', 'Seethammadhara'] },
      { name: 'Visakhapatnam South', mandals: ['Maharanipeta', 'Jagadamba', 'One Town'] },
      { name: 'Visakhapatnam North', mandals: ['Muralinagar', 'Kancharapalem', 'Akkayyapalem'] },
      { name: 'Visakhapatnam West', mandals: ['Gopalapatnam', 'Malkapuram', 'Scindia'] },
      { name: 'Gajuwaka', mandals: ['Gajuwaka', 'Pedagantyada'] },
      { name: 'Pendurthi', mandals: ['Pendurthi', 'Sabbavaram', 'Parawada'] },
    ],
  },
  {
    district: 'Anakapalli',
    code: 'AP-AKP',
    constituencies: [
      { name: 'Chodavaram', mandals: ['Chodavaram', 'Butchayyapeta', 'Ravikamatham', 'Rolugunta'] },
      { name: 'Madugula', mandals: ['Madugula', 'Cheedikada', 'Devarapalli', 'K.Kotapadu'] },
      { name: 'Anakapalli', mandals: ['Anakapalli', 'Kasimkota'] },
      { name: 'Yelamanchili', mandals: ['Yelamanchili', 'Rambilli', 'Munagapaka', 'Atchutapuram'] },
      { name: 'Payakaraopet', mandals: ['Payakaraopet', 'Kotauratla', 'Nakkapalli', 'S.Rayavaram'] },
      { name: 'Narsipatnam', mandals: ['Narsipatnam', 'Golugonda', 'Makavarapalem', 'Nathavaram'] },
    ],
  },
  {
    district: 'Kakinada',
    code: 'AP-KKD',
    constituencies: [
      { name: 'Tuni', mandals: ['Tuni', 'Thondangi', 'Kotananduru'] },
      { name: 'Prathipadu', mandals: ['Prathipadu', 'Sankhavaram', 'Yeleswaram', 'Rowthulapudi'] },
      { name: 'Pithapuram', mandals: ['Pithapuram', 'Gollaprolu', 'U.Kothapalli'] },
      { name: 'Kakinada Rural', mandals: ['Kakinada Rural', 'Karapa'] },
      { name: 'Peddapuram', mandals: ['Peddapuram', 'Samalkota'] },
      { name: 'Kakinada City', mandals: ['Kakinada Urban'] },
      { name: 'Jaggampeta', mandals: ['Jaggampeta', 'Gandepalli', 'Gokavaram', 'Kirlampudi'] },
    ],
  },
  {
    district: 'Dr. B.R. Ambedkar Konaseema',
    code: 'AP-KNS',
    constituencies: [
      { name: 'Ramachandrapuram', mandals: ['Ramachandrapuram', 'Kajuluru', 'K. Gangavaram'] },
      { name: 'Mummidivaram', mandals: ['Mummidivaram', 'I. Polavaram', 'Katrenikona', 'Thallarevu'] },
      { name: 'Amalapuram', mandals: ['Amalapuram', 'Allavaram', 'Uppalaguptam'] },
      { name: 'Razole', mandals: ['Razole', 'Malikipuram', 'Sakhinetipalli', 'Mamidikuduru'] },
      { name: 'Gannavaram (Konaseema)', mandals: ['P.Gannavaram', 'Ambajipeta', 'Ainavilli'] },
      { name: 'Kothapeta', mandals: ['Kothapeta', 'Ravulapalem', 'Atreyapuram', 'Alamuru'] },
      { name: 'Mandapeta', mandals: ['Mandapeta', 'Rayavaram', 'Kapileswarapuram'] },
    ],
  },
  {
    district: 'East Godavari',
    code: 'AP-EG',
    constituencies: [
      { name: 'Anaparthy', mandals: ['Anaparthy', 'Biccavolu', 'Pedapudi', 'Rangampeta'] },
      { name: 'Rajanagaram', mandals: ['Rajanagaram', 'Seethanagaram', 'Korukonda'] },
      { name: 'Rajamahendravaram City', mandals: ['Rajamahendravaram Urban'] },
      { name: 'Rajamahendravaram Rural', mandals: ['Rajamahendravaram Rural', 'Kadiam'] },
      { name: 'Kovvur', mandals: ['Kovvur', 'Chagallu', 'Tallapudi'] },
      { name: 'Nidadavole', mandals: ['Nidadavole', 'Undrajavaram', 'Peravali'] },
      { name: 'Gopalapuram', mandals: ['Gopalapuram', 'Devarapalli', 'Nallajerla', 'Dwarakatirumala'] },
    ],
  },
  {
    district: 'West Godavari',
    code: 'AP-WG',
    constituencies: [
      { name: 'Achanta', mandals: ['Achanta', 'Penugonda', 'Penumantra', 'Poduru'] },
      { name: 'Palakollu', mandals: ['Palakollu', 'Yelamanchili', 'Narasapuram Rural'] },
      { name: 'Narasapuram', mandals: ['Narasapuram', 'Mogalthur'] },
      { name: 'Bhimavaram', mandals: ['Bhimavaram', 'Veeravasaram'] },
      { name: 'Undi', mandals: ['Undi', 'Akividu', 'Palacoderu', 'Kalla'] },
      { name: 'Tanuku', mandals: ['Tanuku', 'Attili', 'Iragavaram'] },
      { name: 'Tadepalligudem', mandals: ['Tadepalligudem', 'Pentapadu'] },
    ],
  },
  {
    district: 'Eluru',
    code: 'AP-ELR',
    constituencies: [
      { name: 'Unguturu', mandals: ['Unguturu', 'Bhimadole', 'Nidamarru', 'Ganapavaram'] },
      { name: 'Denduluru', mandals: ['Denduluru', 'Pedavegi', 'Pedapadu'] },
      { name: 'Eluru', mandals: ['Eluru Urban', 'Eluru Rural'] },
      { name: 'Polavaram', mandals: ['Polavaram', 'Buttaya Gudem', 'Jeelugumilli', 'Koyyalagudem', 'T.Narasapuram', 'Kukunoor', 'Velerupadu'] },
      { name: 'Chintalapudi', mandals: ['Chintalapudi', 'Lingapalem', 'Kamavarapukota', 'Jangareddygudem'] },
      { name: 'Nuzvid', mandals: ['Nuzvid', 'Agiripalli', 'Chatrai', 'Musunuru'] },
      { name: 'Kaikalur', mandals: ['Kaikalur', 'Mandavalli', 'Kalidindi', 'Mudinepalli'] },
    ],
  },
  {
    district: 'Krishna',
    code: 'AP-KRS',
    constituencies: [
      { name: 'Gannavaram', mandals: ['Gannavaram', 'Bapulapadu', 'Unguturu (Krishna)'] },
      { name: 'Gudivada', mandals: ['Gudivada', 'Gudlavalleru', 'Nandivada'] },
      { name: 'Pedana', mandals: ['Pedana', 'Guduru', 'Bantumilli', 'Kruthivennu'] },
      { name: 'Machilipatnam', mandals: ['Machilipatnam Urban', 'Machilipatnam Rural'] },
      { name: 'Avanigadda', mandals: ['Avanigadda', 'Challapalli', 'Mopidevi', 'Nagayalanka', 'Koduru', 'Ghantasala'] },
      { name: 'Pamarru', mandals: ['Pamarru', 'Pamidimukkala', 'Thotlavalluru', 'Pedaparupudi', 'Movva'] },
      { name: 'Penamaluru', mandals: ['Penamaluru', 'Kankipadu', 'Vuyyuru'] },
    ],
  },
  {
    district: 'NTR (Vijayawada)',
    code: 'AP-NTR',
    constituencies: [
      { name: 'Tiruvuru', mandals: ['Tiruvuru', 'A.Konduru', 'Gampalagudem', 'Vissannapeta'] },
      { name: 'Vijayawada West', mandals: ['Vijayawada West Urban', 'Bhavanipuram'] },
      { name: 'Vijayawada Central', mandals: ['Vijayawada Central Mandal', 'Satyanarayanapuram'] },
      { name: 'Vijayawada East', mandals: ['Vijayawada East Urban', 'Patamata', 'Benz Circle'] },
      { name: 'Mylavaram', mandals: ['Mylavaram Mandal', 'Ibrahimpatnam Mandal', 'G.Konduru', 'Reddigudem', 'Vijayawada Rural'] },
      { name: 'Nandigama', mandals: ['Nandigama', 'Kanchikacherla', 'Chandarlapadu', 'Veerullapadu'] },
      { name: 'Jaggayyapeta', mandals: ['Jaggayyapeta', 'Vatsavai', 'Penuganchiprolu'] },
    ],
  },
  {
    district: 'Guntur',
    code: 'AP-GNT',
    constituencies: [
      { name: 'Tadikonda', mandals: ['Tadikonda', 'Thullur', 'Phirangipuram', 'Medikonduru'] },
      { name: 'Mangalagiri', mandals: ['Mangalagiri Mandal', 'Tadepalli Mandal', 'Duggirala'] },
      { name: 'Ponnuru', mandals: ['Ponnuru', 'Chebrolu', 'Pedakakani'] },
      { name: 'Tenali', mandals: ['Tenali', 'Kollipara'] },
      { name: 'Prathipadu (Guntur)', mandals: ['Prathipadu', 'Vatticherukuru', 'Pedanandipadu', 'Kakumanu'] },
      { name: 'Guntur West', mandals: ['Guntur West Mandal'] },
      { name: 'Guntur East', mandals: ['Guntur East Mandal'] },
    ],
  },
  {
    district: 'Bapatla',
    code: 'AP-BPT',
    constituencies: [
      { name: 'Vemuru', mandals: ['Vemuru', 'Kollur', 'Tsundur', 'Bhattiprolu', 'Amruthalur'] },
      { name: 'Repalle', mandals: ['Repalle', 'Nizampatnam', 'Nagaram', 'Cherukupalli'] },
      { name: 'Bapatla', mandals: ['Bapatla', 'Pittalavanipalem', 'Karlapalem'] },
      { name: 'Parchur', mandals: ['Parchur', 'Yeddanapudi', 'Karamchedu', 'Inkollu', 'Chinaganjam', 'Martur'] },
      { name: 'Addanki', mandals: ['Addanki', 'J.Panguluru', 'Santhamaguluru', 'Ballikurava', 'Korisapadu'] },
      { name: 'Chirala', mandals: ['Chirala', 'Vetapalem'] },
    ],
  },
  {
    district: 'Palnadu',
    code: 'AP-PLD',
    constituencies: [
      { name: 'Pedakurapadu', mandals: ['Pedakurapadu', 'Atchampet', 'Krosuru', 'Amaravathi', 'Bellamkonda'] },
      { name: 'Chilakaluripet', mandals: ['Chilakaluripet', 'Nadendla', 'Edlapadu'] },
      { name: 'Narasaraopet', mandals: ['Narasaraopet', 'Rompicherla'] },
      { name: 'Sattenapalle', mandals: ['Sattenapalle', 'Rajupalem', 'Nekarikallu', 'Muppalla'] },
      { name: 'Vinukonda', mandals: ['Vinukonda', 'Bollapalli', 'Nuzendla', 'Savalyapuram', 'Ipuru'] },
      { name: 'Gurazala', mandals: ['Gurazala', 'Dachepalli', 'Piduguralla', 'Machavaram'] },
      { name: 'Macherla', mandals: ['Macherla', 'Veldurthi', 'Durgi', 'Rentachintala', 'Karempudi'] },
    ],
  },
  {
    district: 'Prakasam',
    code: 'AP-PKM',
    constituencies: [
      { name: 'Yerragondapalem', mandals: ['Yerragondapalem', 'Pullalacheruvu', 'Tripuranthakam', 'Dornala', 'Peda Araveedu'] },
      { name: 'Darsi', mandals: ['Darsi', 'Donakonda', 'Kurichedu', 'Mundlamuru', 'Thallur'] },
      { name: 'Santhanuthalapadu', mandals: ['Santhanuthalapadu', 'Chimakurthy', 'Maddipadu', 'Naguluppalapadu'] },
      { name: 'Ongole', mandals: ['Ongole', 'Kothapatnam'] },
      { name: 'Kondapi', mandals: ['Kondapi', 'Singarayakonda', 'Tangutur', 'Jarugumalli', 'Ponnaluru', 'Marripudi'] },
      { name: 'Markapuram', mandals: ['Markapuram', 'Konakanamitla', 'Podili', 'Tarlupadu'] },
      { name: 'Giddalur', mandals: ['Giddalur', 'Bestavaripeta', 'Racherla', 'Komarolu', 'Cumbum', 'Ardhaveedu'] },
      { name: 'Kanigiri', mandals: ['Kanigiri', 'Hanumanthuni Padu', 'Veligandla', 'Pedacherlo Palle', 'Chandrasekharapuram', 'Pamur'] },
    ],
  },
  {
    district: 'SPSR Nellore',
    code: 'AP-NLR',
    constituencies: [
      { name: 'Kandukur', mandals: ['Kandukur', 'Lingasamudram', 'Gudluru', 'Ulavapadu', 'Voletivaripalem'] },
      { name: 'Kavali', mandals: ['Kavali', 'Bogole', 'Allur', 'Dagadarthi'] },
      { name: 'Atmakur', mandals: ['Atmakur', 'Chejerla', 'Anumasamudrampeta', 'Marripadu', 'Sangam', 'Ananthasagaram'] },
      { name: 'Kovur', mandals: ['Kovur', 'Buchireddypalem', 'Indukurpet', 'Vidavalur', 'Kodavalur'] },
      { name: 'Nellore City', mandals: ['Nellore Urban Mandal'] },
      { name: 'Nellore Rural', mandals: ['Nellore Rural'] },
      { name: 'Sarvepalli', mandals: ['Podalakur', 'Thotapalligudur', 'Muthukur', 'Venkatachalam', 'Manubolu'] },
      { name: 'Udayagiri', mandals: ['Udayagiri', 'Seetharamapuram', 'Varikuntapadu', 'Kaligiri', 'Vinjamur', 'Duttalur', 'Kondapuram', 'Jaladanki'] },
    ],
  },
  {
    district: 'Kurnool',
    code: 'AP-KNL',
    constituencies: [
      { name: 'Kurnool Urban', mandals: ['Kurnool Urban Mandal', 'Kallur Mandal'] },
      { name: 'Pattikonda', mandals: ['Pattikonda', 'Maddikera East', 'Tuggali', 'Veldurthi', 'Krishnagiri'] },
      { name: 'Kodumur', mandals: ['Kodumur Mandal', 'C.Belagal', 'Gudur'] },
      { name: 'Yemmiganur', mandals: ['Yemmiganur', 'Nandavaram', 'Gonegandla'] },
      { name: 'Mantralayam', mandals: ['Mantralayam', 'Kosigi', 'Kowthalam', 'Pedda Kadubur'] },
      { name: 'Adoni', mandals: ['Adoni'] },
      { name: 'Alur', mandals: ['Alur', 'Aspari', 'Devanakonda', 'Holagunda', 'Halaharvi', 'Chippagiri'] },
    ],
  },
  {
    district: 'Nandyal',
    code: 'AP-NDL',
    constituencies: [
      { name: 'Allagadda', mandals: ['Allagadda', 'Sirvel', 'Dornipadu', 'Uyyalawada', 'Chagalamarri', 'Rudravaram'] },
      { name: 'Srisailam', mandals: ['Srisailam', 'Atmakur (Nandyal)', 'Velgode', 'Bandi Atmakur', 'Mahanandi'] },
      { name: 'Nandikotkur', mandals: ['Nandikotkur', 'Pagidyala', 'Jupadu Bungalow', 'Kothapalle', 'Pamulapadu', 'Midthur'] },
      { name: 'Panyam', mandals: ['Panyam', 'Gadivemula', 'Orvakal'] },
      { name: 'Nandyal', mandals: ['Nandyal Urban', 'Nandyal Rural', 'Gospadu'] },
      { name: 'Banaganapalle', mandals: ['Banaganapalle', 'Owk', 'Koilkuntla', 'Sanjamala', 'Kolimigundla'] },
      { name: 'Dhone', mandals: ['Dhone', 'Bethamcherla', 'Peapully'] },
    ],
  },
  {
    district: 'Anantapuramu',
    code: 'AP-ATP',
    constituencies: [
      { name: 'Rayadurg', mandals: ['Rayadurg', 'D.Hirehal', 'Kanekal', 'Bommanahal', 'Gummagatta'] },
      { name: 'Uravakonda', mandals: ['Uravakonda', 'Vidapanakal', 'Vajrakarur', 'Guntakal Rural', 'Beluguppa', 'Kudair'] },
      { name: 'Guntakal', mandals: ['Guntakal', 'Gooty', 'Pamidi'] },
      { name: 'Tadipatri', mandals: ['Tadipatri', 'Yellanur', 'Putlur', 'Peddapappur'] },
      { name: 'Singanamala', mandals: ['Singanamala', 'Garladinne', 'Putlur', 'Narpala', 'Bukkarayasamudram', 'Yadiki'] },
      { name: 'Anantapur Urban', mandals: ['Anantapuramu Urban Mandal', 'Anantapur Rural'] },
      { name: 'Kalyandurg', mandals: ['Kalyandurg', 'Brahmasamudram', 'Settur', 'Kundurpi', 'Kambadur'] },
      { name: 'Raptadu', mandals: ['Raptadu', 'Atmakur (Anantapur)', 'Kanaganapalli', 'Ck Palli', 'Ramagiri'] },
    ],
  },
  {
    district: 'Sri Sathya Sai',
    code: 'AP-SSS',
    constituencies: [
      { name: 'Madakasira', mandals: ['Madakasira', 'Amarapuram', 'Gudibanda', 'Rolla', 'Agali'] },
      { name: 'Hindupur', mandals: ['Hindupur', 'Lepakshi', 'Chilamathur'] },
      { name: 'Penukonda', mandals: ['Penukonda', 'Parigi', 'Gorantla', 'Somandepalli', 'Roddam'] },
      { name: 'Puttaparthi', mandals: ['Puttaparthi', 'Nallamada', 'Bukkapatnam', 'Kothacheruvu', 'Obuladevaracheruvu', 'Amadagur'] },
      { name: 'Dharmavaram', mandals: ['Dharmavaram', 'Bathalapalli', 'Tadimarri', 'Mudigubba'] },
      { name: 'Kadiri', mandals: ['Kadiri', 'Tanakal', 'Nambulipulikunta', 'Gandlapenta', 'Nallacheruvu', 'Talupula'] },
    ],
  },
  {
    district: 'YSR Kadapa',
    code: 'AP-KDP',
    constituencies: [
      { name: 'Badvel', mandals: ['Badvel', 'Gopavaram', 'B.Kodur', 'Sri Avadhutha Kasinayana', 'Porumamilla', 'Kalasapadu', 'Atlur'] },
      { name: 'Kadapa', mandals: ['Kadapa Urban', 'Kadapa Rural'] },
      { name: 'Pulivendula', mandals: ['Pulivendula', 'Simhadripuram', 'Lingala', 'Thondur', 'Vempalli', 'Vemula', 'Chakrayapet'] },
      { name: 'Kamalapuram', mandals: ['Kamalapuram', 'Vallur', 'Chinthakommadinne', 'Pendlimarri', 'Veerapunayunipalle', 'Yerraguntla'] },
      { name: 'Jammalamadugu', mandals: ['Jammalamadugu', 'Peddamudium', 'Mylavaram (Kadapa)', 'Kondapuram', 'Muddanur', 'Thondur'] },
      { name: 'Proddatur', mandals: ['Proddatur', 'Rajupalem (Kadapa)'] },
      { name: 'Mydukur', mandals: ['Mydukur', 'Duvvur', 'Chapad', 'Khajipet', 'Brahmamgarimattam'] },
    ],
  },
  {
    district: 'Annamayya',
    code: 'AP-ANM',
    constituencies: [
      { name: 'Rajampet', mandals: ['Rajampet', 'Nandalur', 'Veeraballi', 'T. Sundupalli', 'Vontimitta', 'Sidhout'] },
      { name: 'Kodur', mandals: ['Railway Koduru', 'Chitvel', 'Pullampeta', 'Obulavaripalle', 'Penagalur'] },
      { name: 'Rayachoti', mandals: ['Rayachoti', 'Sambepalli', 'Chinnamandyam', 'Galiveedu', 'Lakkireddipalli', 'Ramapuram'] },
      { name: 'Thamballapalle', mandals: ['Thamballapalle', 'Mulakalacheruvu', 'Peddamandyam', 'Kurabalakota', 'Peddathippasamudram', 'B.Kothakota'] },
      { name: 'Pileru', mandals: ['Pileru', 'Gurramkonda', 'Kalakada', 'Kambhamvaripalle', 'Valmiki Puram', 'Kalikiri'] },
      { name: 'Madanapalle', mandals: ['Madanapalle', 'Nimmanapalle', 'Ramasamudram'] },
    ],
  },
  {
    district: 'Chittoor',
    code: 'AP-CTR',
    constituencies: [
      { name: 'Punganur', mandals: ['Punganur', 'Chowdepalle', 'Sodam', 'Somala', 'Peddapanjani', 'Rompicherla'] },
      { name: 'Nagari', mandals: ['Nagari', 'Nindra', 'Vijayapuram', 'Putthur', 'Vadamalapeta'] },
      { name: 'Gangadhara Nellore', mandals: ['Gangadhara Nellore', 'Penumuru', 'Vedurukuppam', 'Srirangarajapuram', 'Palasamudram', 'Karvetinagar'] },
      { name: 'Chittoor', mandals: ['Chittoor', 'Gudipala'] },
      { name: 'Puthalapattu', mandals: ['Puthalapattu', 'Irala', 'Thavanampalle', 'Bangarupalem', 'Yadamari'] },
      { name: 'Palamaner', mandals: ['Palamaner', 'Gangavaram (Chittoor)', 'Baireddipalle', 'Venkatagirikota', 'Pedda Panjani'] },
      { name: 'Kuppam', mandals: ['Kuppam', 'Gudupalle', 'Shanthipuram', 'Ramakuppam'] },
    ],
  },
  {
    district: 'Tirupati',
    code: 'AP-TPT',
    constituencies: [
      { name: 'Srikalahasti', mandals: ['Srikalahasti', 'Thottambedu', 'Renigunta', 'Yerpedu'] },
      { name: 'Satyavedu', mandals: ['Satyavedu', 'Varadaiahpalem', 'Buchinaidu Kandriga', 'Nagalapuram', 'Pitchatur', 'Narayanavanam', 'K.V.B.Puram'] },
      { name: 'Gudur', mandals: ['Gudur', 'Chillakur', 'Kota', 'Vakadu', 'Chittamur'] },
      { name: 'Sullurpeta', mandals: ['Sullurpeta', 'Tada', 'Doravarisatram', 'Pellakur', 'Naidupeta', 'Ojili'] },
      { name: 'Venkatagiri', mandals: ['Venkatagiri', 'Kaluvoya', 'Rapur', 'Sydapuram', 'Dakkili', 'Balayapalli'] },
      { name: 'Tirupati', mandals: ['Tirupati Urban Mandal'] },
      { name: 'Chandragiri', mandals: ['Chandragiri Mandal', 'Tirupati Rural', 'Pakala', 'Ramachandrapuram (Tirupati)', 'Chinnagottigallu', 'Yerravaripalem'] },
    ],
  },
];
